[server]
maxUploadSize = 5000

[theme]
base = "light"
primaryColor = "#E60012"  # (選填) Aurotek 紅色，讓按鈕跟 Logo 更搭
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"
font = "sans serif"