[server]
maxUploadSize = 5000

[theme]
base = "light"
# [修改] 將原本的紅色改為深藍色
primaryColor = "#0E4E8C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"
font = "sans serif"